import Head from 'next/head'
import Navbar from '../../components/navbar'
import Menubar from '../../components/menubar'
import LocalStorage from '../../components/localStorage';




export default function Favories() {
    return (
    <>
      <Head>
        <title>Foodies 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar />
      <Navbar />
      <LocalStorage />
      
    </>
  )
}