import Head from 'next/head'
import Navbar from '../../components/navbar'
import Menubar from '../../components/menubar'
import Title from '../../components/title'
import Results from '../../components/results'
import requests from "../../utils/request"

export default function Home({results}) {
  // console.log(results)
  return (
    <>
      <Head>
        <title>Foodies 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menubar />
      <Navbar />
      <Title />
      <Results results={results}/>
    </>
  )
}

export async function getServerSideProps(context) {
  const search = context.query.search;

  const results = await fetch(
    'https://themealdb.com/api/json/v1/1/search.php?s=beef'
  ).then((res) => res.json());

  return {
    props: {
      results
    },
  };


  // const search = context.query.search;

  // const request = await fetch(
  //   `https://themealdb.com/api${
  //     requests[search]?.url || requests.fetchBeef.url
  //   }`
  // ).then((res) => res.json());

  // return {
  //   props: {
  //    results: request.result ?? null,
  //   },
  // };
}
