import Head from 'next/head'
import Link from "next/link";
import Image from "next/image";
import Cover from "../../public/images/cover.jpg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Foodies 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 sm:grid-cols-2 h-screen w-full">
      <div className="hidden sm:block h-fit w-full">
        <Image
          priority="true"
          className=" w-full object-cover"
          src={Cover}
          alt="Food"
        />
      </div>
      <div className="bg-gray-600 flex flex-col justify-center pb-64">
        <form
          className="max-w-[400px] w-full mx-auto bg-gray-900 p-8 px-8 rounded-lg"
          action="/api/login"
          method="Post"
        >
          <h2 className="text-4xl text-white font-bold text-center">SIGN IN</h2>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Email</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none"
              name="email"
              type="text"
            />
          </div>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Password</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none"
              name="password"
              type="password"
              autoComplete='current-Password'
            />
          </div>
          <div className="flex flex-col text-gray-400 py-1 text-center">
            <button
              onClick={() => Cookies.set("loggedin", true)}
              className="border rounded-xl bg-teal-500 w-full p-1 my-5 hover:bg-teal-400 text-white"
            >
              Log In
            </button>
          </div>
          <p className="text-center text-white font-bold">
            If you do not have an account please
          </p>
          <div className="text-center text-white font-bold m-2 ">
            <Link  href="signup">
              Signup
            </Link>
          </div>
        </form>
      </div>
    </div>
    </>
  )
}
