import Menubar from '../../components/menubar';
import React, {useState} from 'react'
import Navbar from '../../components/navbar';
import Head from 'next/head';
import axios from "axios";
import { ImSearch } from "react-icons/im";

const API_KEY = process.env.API_KEY;
const API_ID = process.env.API_ID;


function Search() {
    const [query, setQuery] = useState('')
    const [recipe, setRecipe] = useState("");

    const options = {
        method: "GET",
        url: `https://api.edamam.com/api/recipes/v2?type=public&q=${query}&app_id=${API_ID}&app_key=${API_KEY}`,
      };

      const getRecipe = (e) => {
        e.preventDefault();
        setLoading(true);
        axios
          .request(options)
          .then(function (response) {
            setRecipe(response.data);
            setQuery("");
            setLoading(false);
          })
          .catch(function (error) {
            console.error(error);
          });
      };
  return (
    <>
    <Head>
        <title>Foodies 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Menubar />
    <Navbar />
      <div className="p-4 justify-center">
        <div className="relative flex items-center justify-center max-w-[500px] w-full m-auto pt-4 z-10 ">
          <form
            onSubmit={getRecipe}
            className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-400 text-white  rounded-2xl"
          >
            <div>
              <input
                onChange={(e) => setQuery(e.target.value)}
                className="bg-transparent border border-gray-400 text-white focus:outline-none text-2xl"
                type="text"
                placeholder="Search for a recipe"
                value={query}
              />
            </div>
            <button onClick={getRecipe}>
              <ImSearch />
            </button>
          </form>
        </div>
      </div>
    </>
  )
}

export default Search;